const FB_URL='https://world-cup-2026-d3091-default-rtdb.europe-west1.firebasedatabase.app';
const USER_KEY='ucl_azba_user';
const TEAMS={
  'السعودية':{flag:'🇸🇦',group:'A'},'العراق':{flag:'🇮🇶',group:'A'},'عُمان':{flag:'🇴🇲',group:'A'},'الكويت':{flag:'🇰🇼',group:'A'},
  'الإمارات':{flag:'🇦🇪',group:'B'},'قطر':{flag:'🇶🇦',group:'B'},'البحرين':{flag:'🇧🇭',group:'B'},'اليمن':{flag:'🇾🇪',group:'B'}
};
const GROUPS={A:['السعودية','العراق','عُمان','الكويت'],B:['الإمارات','قطر','البحرين','اليمن']};
let MATCHES=[];
let currentUserId=localStorage.getItem(USER_KEY)||'';
let myPreds={},allPreds={},results={},users={},newsItems=[];
function el(id){return document.getElementById(id)}
async function fbGet(path){try{const r=await fetch(`${FB_URL}/${path}.json`);return r.ok?await r.json():null}catch{return null}}
async function fbPut(path,val){try{const r=await fetch(`${FB_URL}/${path}.json`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(val)});return r.ok}catch{return false}}
function fmtDate(iso){return new Intl.DateTimeFormat('ar-OM',{weekday:'long',day:'numeric',month:'long',hour:'numeric',minute:'2-digit',hour12:true,timeZone:'Asia/Muscat'}).format(new Date(iso))}
function flag(name){return TEAMS[name]?.flag||'🏆'}
function isOpen(m){if(m.predictable===false)return false;const now=Date.now(),ko=new Date(m.ko).getTime();return now>=ko-24*60*60*1000&&now<ko-30*60*1000}
function isLocked(m){return Date.now()>=new Date(m.ko).getTime()-30*60*1000}
function toast(t){const x=el('toast');if(!x)return;x.textContent=t;x.classList.add('show');clearTimeout(window.__gToast);window.__gToast=setTimeout(()=>x.classList.remove('show'),2200)}
function stageName(m){if(m.stage==='semifinal')return 'نصف النهائي';if(m.stage==='final')return 'النهائي';return `الجولة ${m.md}`}
function scorePrediction(p,r){if(!p||!r||!Number.isInteger(Number(r.h))||!Number.isInteger(Number(r.a)))return 0;const ph=Number(p.h),pa=Number(p.a),rh=Number(r.h),ra=Number(r.a);if(ph===rh&&pa===ra)return 3;const po=Math.sign(ph-pa),ro=Math.sign(rh-ra);return po===ro?1:0}
function tableFor(group){const rows={};GROUPS[group].forEach(t=>rows[t]={team:t,p:0,w:0,d:0,l:0,gf:0,ga:0,gd:0,pts:0});MATCHES.filter(m=>m.group===group).forEach(m=>{const r=results[m.id];if(!r||!Number.isInteger(Number(r.h))||!Number.isInteger(Number(r.a)))return;const h=rows[m.home],a=rows[m.away],rh=Number(r.h),ra=Number(r.a);if(!h||!a)return;h.p++;a.p++;h.gf+=rh;h.ga+=ra;a.gf+=ra;a.ga+=rh;if(rh>ra){h.w++;a.l++;h.pts+=3}else if(rh<ra){a.w++;h.l++;a.pts+=3}else{h.d++;a.d++;h.pts++;a.pts++}});Object.values(rows).forEach(x=>x.gd=x.gf-x.ga);return Object.values(rows).sort((a,b)=>b.pts-a.pts||b.gd-a.gd||b.gf-a.gf||a.team.localeCompare(b.team,'ar'))}
function renderGroups(){const host=el('groupsGrid');if(!host)return;host.innerHTML=Object.entries(GROUPS).map(([g])=>{const rows=tableFor(g);return `<div class="group-card"><h3>المجموعة ${g==='A'?'الأولى':'الثانية'}</h3><div class="stand-head"><span>المنتخب</span><span>ل</span><span>ف.أ</span><span>ن</span></div>${rows.map((r,i)=>`<div class="stand-row"><span><b>${i+1}</b> <span class="mini-flag">${flag(r.team)}</span>${r.team}</span><span>${r.p}</span><span>${r.gd>0?'+'+r.gd:r.gd}</span><strong>${r.pts}</strong></div>`).join('')}</div>`}).join('')}
function renderTeams(){const host=el('teamsGrid');if(!host)return;host.innerHTML=Object.entries(TEAMS).map(([n,m])=>`<div class="team-card"><div class="flag">${m.flag}</div><div><strong>${n}</strong><small>المجموعة ${m.group}</small></div></div>`).join('')}
function matchCard(m){const p=myPreds[m.id]||{},open=isOpen(m),locked=isLocked(m),r=results[m.id];const placeholder=m.predictable===false;const state=r&&Number.isInteger(Number(r.h))?'انتهت':placeholder?'يتحدد بعد دور المجموعات':open?'التوقع مفتوح':locked?'مغلق':'يفتح قبل 24 ساعة';const resultHtml=r&&Number.isInteger(Number(r.h))?`<div class="final-score">${r.h} - ${r.a}</div>`:'<div class="vs">VS</div>';const form=placeholder?'':`<div class="predict-row"><input class="score-input" id="h_${m.id}" type="number" min="0" max="20" inputmode="numeric" placeholder="${m.home}" value="${p.h??''}" ${open?'':'disabled'}><input class="score-input" id="a_${m.id}" type="number" min="0" max="20" inputmode="numeric" placeholder="${m.away}" value="${p.a??''}" ${open?'':'disabled'}><button class="save-pred" onclick="savePrediction('${m.id}')" ${open?'':'disabled'}>حفظ</button></div><div class="pred-note">${open?'يمكنك تعديل توقعك حتى 30 دقيقة قبل البداية':locked?'انتهت مهلة التوقع':'سيُفتح التوقع تلقائياً قبل المباراة بـ24 ساعة'}</div>`;return `<article class="match-card"><div class="match-top"><span>${stageName(m)}</span><span class="match-status">${state}</span></div><div class="match-teams"><div class="team-side"><div class="flag">${flag(m.home)}</div><strong>${m.home}</strong></div>${resultHtml}<div class="team-side"><div class="flag">${flag(m.away)}</div><strong>${m.away}</strong></div></div><div class="match-meta">${fmtDate(m.ko)} بتوقيت مسقط · ${m.venue}</div>${form}</article>`}
function renderMatches(){const host=el('matchesList');if(!host)return;host.innerHTML=MATCHES.map(matchCard).join('');if(el('openPredictions'))el('openPredictions').textContent=MATCHES.filter(isOpen).length;if(el('myPredictions'))el('myPredictions').textContent=Object.keys(myPreds).length}
async function savePrediction(id){if(!currentUserId){el('loginGate')?.classList.remove('hidden');return}const m=MATCHES.find(x=>x.id===id);if(!m||!isOpen(m)){toast('التوقع غير متاح الآن');return}const h=Number(el(`h_${id}`).value),a=Number(el(`a_${id}`).value);if(!Number.isInteger(h)||!Number.isInteger(a)||h<0||a<0){toast('أدخل نتيجة صحيحة');return}const val={h,a,updatedAt:Date.now(),matchday:m.md,home:m.home,away:m.away};const ok=await fbPut(`gulfCup27Predictions/${currentUserId}/${id}`,val);if(ok){myPreds[id]=val;allPreds[currentUserId]=myPreds;renderMatches();renderRanking();toast('تم حفظ توقعك ✅')}else toast('تعذر حفظ التوقع')}
function renderRanking(){const host=el('rankingList');if(!host)return;const rows=Object.entries(allPreds||{}).map(([uid,preds])=>{let pts=0,exact=0,correct=0;Object.entries(preds||{}).forEach(([mid,p])=>{const s=scorePrediction(p,results[mid]);pts+=s;if(s===3)exact++;else if(s===1)correct++});return{uid,name:users?.[uid]?.nickname||users?.[uid]?.name||'مشارك',pts,exact,correct,count:Object.keys(preds||{}).length}}).sort((a,b)=>b.pts-a.pts||b.exact-a.exact||a.name.localeCompare(b.name,'ar'));host.innerHTML=rows.length?rows.map((r,i)=>`<div class="rank-row ${r.uid===currentUserId?'me':''}"><span class="rank-no">${i+1}</span><div class="rank-name"><strong>${r.name}</strong><small>${r.count} توقع · ${r.exact} دقيقة</small></div><strong class="rank-pts">${r.pts} ن</strong></div>`).join(''):'<div class="empty-state">يظهر ترتيب التوقعات بعد حفظ أول توقع.</div>'}
function renderNews(){const host=el('newsList');if(!host)return;host.innerHTML=(newsItems||[]).length?newsItems.map(n=>`<a class="news-card" href="${n.link||'#'}" target="_blank" rel="noopener"><span class="news-source">${n.source||'أخبار خليجي 27'}</span><strong>${n.title||''}</strong><small>${n.publishedAt?new Intl.DateTimeFormat('ar-OM',{day:'numeric',month:'short',hour:'numeric',minute:'2-digit'}).format(new Date(Number(n.publishedAt))):''}</small></a>`).join(''):'<div class="empty-state">سيتم تحديث أخبار البطولة والمنتخبات تلقائيًا هنا.</div>'}
function setupTabs(){document.querySelectorAll('.gulf-tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.gulf-tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tab-pane').forEach(x=>x.classList.remove('active'));b.classList.add('active');el(`tab-${b.dataset.tab}`)?.classList.add('active');lucide?.createIcons()}))}
function updateCountdown(){const start=new Date('2026-09-23T17:30:00+03:00').getTime(),d=start-Date.now();if(!el('countdown'))return;if(d<=0){el('countdown').textContent='البطولة انطلقت — أهلًا بالخليج 🇸🇦';return}const days=Math.floor(d/86400000),hrs=Math.floor((d%86400000)/3600000),mins=Math.floor((d%3600000)/60000);el('countdown').textContent=`متبقي على الافتتاح: ${days} يوم · ${hrs} ساعة · ${mins} دقيقة`}
function backToMain(){if(window.parent&&window.parent!==window&&typeof window.parent.closeGulfCup==='function'){window.parent.closeGulfCup();return}location.href='index.html'}
async function refreshGulfScoreboard(){
  try {
    // Check the same Firebase result records that the Cloudflare cron updates.
    const latest=await fbGet('gulfCup27Results');
    if(latest && JSON.stringify(latest)!==JSON.stringify(results)){
      results=latest;
      renderGroups();
      renderMatches();
      renderRanking();
    }
  }catch(err){console.warn('Gulf Cup results refresh:',err)}
}
async function init(){setupTabs();try{const s=await fetch(`gulf-schedule.json?v=${Date.now()}`,{cache:'no-store'}).then(r=>r.json());MATCHES=Array.isArray(s.matches)?s.matches:[]}catch{MATCHES=[]}const data=await Promise.all([currentUserId?fbGet(`gulfCup27Predictions/${currentUserId}`):Promise.resolve({}),fbGet('gulfCup27Predictions'),fbGet('gulfCup27Results'),fbGet('users'),fbGet('gulfCup27News/latest')]);myPreds=data[0]||{};allPreds=data[1]||{};results=data[2]||{};users=data[3]||{};const rawNews=data[4]||[];newsItems=Array.isArray(rawNews)?rawNews:Object.values(rawNews);renderGroups();renderTeams();renderMatches();renderRanking();renderNews();updateCountdown();setInterval(()=>{updateCountdown();renderMatches();if(!document.hidden)refreshGulfScoreboard()},60000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refreshGulfScoreboard()});window.addEventListener('focus',refreshGulfScoreboard);setTimeout(()=>lucide?.createIcons(),100)}
window.savePrediction=savePrediction;window.backToMain=backToMain;document.addEventListener('DOMContentLoaded',init);
